#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2019 Garmin Canada Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.20Release
// Tag = production/akw/21.20.00-0-g5907bff
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace fitsharplib.Fit
{
    /// <summary>
    /// Implements the profile LanguageBits0 type as a class
    /// </summary>
    public static class LanguageBits0 
    {
        public const byte English = 0x01;
        public const byte French = 0x02;
        public const byte Italian = 0x04;
        public const byte German = 0x08;
        public const byte Spanish = 0x10;
        public const byte Croatian = 0x20;
        public const byte Czech = 0x40;
        public const byte Danish = 0x80;
        public const byte Invalid = (byte)0x00;


    }
}

