#region Copyright
/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2023 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.115Release
// Tag = production/release/21.115.00-0-gfe0a7f8
/////////////////////////////////////////////////////////////////////////////////////////////

#endregion


namespace Dynastream.Fit
{
  /// <summary>
  /// Event Args Class associated with the DeveloperFieldDescrtiption Event
  /// </summary>
  public class DeveloperFieldDescriptionEventArgs : EventArgs
  {
    public DeveloperFieldDescription Description { get; private set; }

    public DeveloperFieldDescriptionEventArgs(DeveloperFieldDescription description)
    {
      Description = description;
    }
  }
} // namespace
