#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2019 Garmin Canada Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.20Release
// Tag = production/akw/21.20.00-0-g5907bff
////////////////////////////////////////////////////////////////////////////////

#endregion

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;
using System.IO;

namespace fitsharplib.Fit
{
    // Define our necessary event types (EventArgs and the delegate)
    public delegate void MesgEventHandler(object sender, MesgEventArgs e);
    public delegate void MesgDefinitionEventHandler(object sender, MesgDefinitionEventArgs e);

    public class MesgEventArgs : EventArgs
    {
        public Mesg mesg = null;

        public MesgEventArgs()
        {
        }

        public MesgEventArgs(Mesg newMesg)
        {
            mesg = new Mesg(newMesg);
        }
    }

    public class MesgDefinitionEventArgs : EventArgs
    {
        public MesgDefinition mesgDef = null;

        public MesgDefinitionEventArgs()
        {
        }

        public MesgDefinitionEventArgs(MesgDefinition newDefn)
        {
            mesgDef = new MesgDefinition(newDefn);
        }
    }

    /// <summary>
    /// Manages Mesg and MesgDefinition events.
    /// </summary>
    public class MesgBroadcaster
    {
        public event MesgDefinitionEventHandler MesgDefinitionEvent;
        public event MesgEventHandler MesgEvent;

        public void HandleMessage(object sender, MesgEventArgs e)
        {
            e.mesg = ToSpecificMessage(e.mesg);
            MesgEvent?.Invoke(sender, e);
        }
        
        public void HandleMesgDefinition(object sender, MesgDefinitionEventArgs e)
        {
            MesgDefinitionEvent?.Invoke(sender, e);
        }
        
        private Mesg ToSpecificMessage(Mesg e)
        {
            switch (e.Num)
            {
            case MesgNum.FileId: return new FileIdMesg(e);
            case MesgNum.FileCreator: return new FileCreatorMesg(e);
            case MesgNum.TimestampCorrelation: return new TimestampCorrelationMesg(e);
            case MesgNum.Software: return new SoftwareMesg(e);
            case MesgNum.SlaveDevice: return new SlaveDeviceMesg(e);
            case MesgNum.Capabilities: return new CapabilitiesMesg(e);
            case MesgNum.FileCapabilities: return new FileCapabilitiesMesg(e);
            case MesgNum.MesgCapabilities: return new MesgCapabilitiesMesg(e);
            case MesgNum.FieldCapabilities: return new FieldCapabilitiesMesg(e);
            case MesgNum.DeviceSettings: return new DeviceSettingsMesg(e);
            case MesgNum.UserProfile: return new UserProfileMesg(e);
            case MesgNum.HrmProfile: return new HrmProfileMesg(e);
            case MesgNum.SdmProfile: return new SdmProfileMesg(e);
            case MesgNum.BikeProfile: return new BikeProfileMesg(e);
            case MesgNum.Connectivity: return new ConnectivityMesg(e);
            case MesgNum.WatchfaceSettings: return new WatchfaceSettingsMesg(e);
            case MesgNum.OhrSettings: return new OhrSettingsMesg(e);
            case MesgNum.ZonesTarget: return new ZonesTargetMesg(e);
            case MesgNum.Sport: return new SportMesg(e);
            case MesgNum.HrZone: return new HrZoneMesg(e);
            case MesgNum.SpeedZone: return new SpeedZoneMesg(e);
            case MesgNum.CadenceZone: return new CadenceZoneMesg(e);
            case MesgNum.PowerZone: return new PowerZoneMesg(e);
            case MesgNum.MetZone: return new MetZoneMesg(e);
            case MesgNum.DiveSettings: return new DiveSettingsMesg(e);
            case MesgNum.DiveAlarm: return new DiveAlarmMesg(e);
            case MesgNum.DiveGas: return new DiveGasMesg(e);
            case MesgNum.Goal: return new GoalMesg(e);
            case MesgNum.Activity: return new ActivityMesg(e);
            case MesgNum.Session: return new SessionMesg(e);
            case MesgNum.Lap: return new LapMesg(e);
            case MesgNum.Length: return new LengthMesg(e);
            case MesgNum.Record: return new RecordMesg(e);
            case MesgNum.Event: return new EventMesg(e);
            case MesgNum.DeviceInfo: return new DeviceInfoMesg(e);
            case MesgNum.TrainingFile: return new TrainingFileMesg(e);
            case MesgNum.Hrv: return new HrvMesg(e);
            case MesgNum.WeatherConditions: return new WeatherConditionsMesg(e);
            case MesgNum.WeatherAlert: return new WeatherAlertMesg(e);
            case MesgNum.GpsMetadata: return new GpsMetadataMesg(e);
            case MesgNum.CameraEvent: return new CameraEventMesg(e);
            case MesgNum.GyroscopeData: return new GyroscopeDataMesg(e);
            case MesgNum.AccelerometerData: return new AccelerometerDataMesg(e);
            case MesgNum.MagnetometerData: return new MagnetometerDataMesg(e);
            case MesgNum.BarometerData: return new BarometerDataMesg(e);
            case MesgNum.ThreeDSensorCalibration: return new ThreeDSensorCalibrationMesg(e);
            case MesgNum.OneDSensorCalibration: return new OneDSensorCalibrationMesg(e);
            case MesgNum.VideoFrame: return new VideoFrameMesg(e);
            case MesgNum.ObdiiData: return new ObdiiDataMesg(e);
            case MesgNum.NmeaSentence: return new NmeaSentenceMesg(e);
            case MesgNum.AviationAttitude: return new AviationAttitudeMesg(e);
            case MesgNum.Video: return new VideoMesg(e);
            case MesgNum.VideoTitle: return new VideoTitleMesg(e);
            case MesgNum.VideoDescription: return new VideoDescriptionMesg(e);
            case MesgNum.VideoClip: return new VideoClipMesg(e);
            case MesgNum.Set: return new SetMesg(e);
            case MesgNum.Jump: return new JumpMesg(e);
            case MesgNum.Course: return new CourseMesg(e);
            case MesgNum.CoursePoint: return new CoursePointMesg(e);
            case MesgNum.SegmentId: return new SegmentIdMesg(e);
            case MesgNum.SegmentLeaderboardEntry: return new SegmentLeaderboardEntryMesg(e);
            case MesgNum.SegmentPoint: return new SegmentPointMesg(e);
            case MesgNum.SegmentLap: return new SegmentLapMesg(e);
            case MesgNum.SegmentFile: return new SegmentFileMesg(e);
            case MesgNum.Workout: return new WorkoutMesg(e);
            case MesgNum.WorkoutSession: return new WorkoutSessionMesg(e);
            case MesgNum.WorkoutStep: return new WorkoutStepMesg(e);
            case MesgNum.ExerciseTitle: return new ExerciseTitleMesg(e);
            case MesgNum.Schedule: return new ScheduleMesg(e);
            case MesgNum.Totals: return new TotalsMesg(e);
            case MesgNum.WeightScale: return new WeightScaleMesg(e);
            case MesgNum.BloodPressure: return new BloodPressureMesg(e);
            case MesgNum.MonitoringInfo: return new MonitoringInfoMesg(e);
            case MesgNum.Monitoring: return new MonitoringMesg(e);
            case MesgNum.Hr: return new HrMesg(e);
            case MesgNum.StressLevel: return new StressLevelMesg(e);
            case MesgNum.MemoGlob: return new MemoGlobMesg(e);
            case MesgNum.AntChannelId: return new AntChannelIdMesg(e);
            case MesgNum.AntRx: return new AntRxMesg(e);
            case MesgNum.AntTx: return new AntTxMesg(e);
            case MesgNum.ExdScreenConfiguration: return new ExdScreenConfigurationMesg(e);
            case MesgNum.ExdDataFieldConfiguration: return new ExdDataFieldConfigurationMesg(e);
            case MesgNum.ExdDataConceptConfiguration: return new ExdDataConceptConfigurationMesg(e);
            case MesgNum.FieldDescription: return new FieldDescriptionMesg(e);
            case MesgNum.DeveloperDataId: return new DeveloperDataIdMesg(e);
            case MesgNum.DiveSummary: return new DiveSummaryMesg(e);
            case MesgNum.ClimbPro: return new ClimbProMesg(e);
            case MesgNum.Pad: return new PadMesg(e);
            
            default:
                return e;
            }
        }
        
    } // Class
} // namespace
