#region Copyright
////////////////////////////////////////////////////////////////////////////////
// The following FIT Protocol software provided may be used with FIT protocol
// devices only and remains the copyrighted property of Garmin Canada Inc.
// The software is being provided on an "as-is" basis and as an accommodation,
// and therefore all warranties, representations, or guarantees of any kind
// (whether express, implied or statutory) including, without limitation,
// warranties of merchantability, non-infringement, or fitness for a particular
// purpose, are specifically disclaimed.
//
// Copyright 2019 Garmin Canada Inc.
////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.20Release
// Tag = production/akw/21.20.00-0-g5907bff
////////////////////////////////////////////////////////////////////////////////

#endregion

namespace Dauer.Data.Fit
{
    /// <summary>
    /// Implements the profile ActivityType type as an enum
    /// </summary>
    public enum ActivityType : byte
    {
        Generic = 0,
        Running = 1,
        Cycling = 2,
        Transition = 3,
        FitnessEquipment = 4,
        Swimming = 5,
        Walking = 6,
        Sedentary = 8,
        All = 254,
        Invalid = 0xFF


    }
}

